CREATE TABLE users(
	id UUID PRIMARY KEY NOT NULL,
	email VARCHAR(255) UNIQUE NOT NULL,
	password VARCHAR(255) NOT NULL,
	created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
	updated_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL
);

CREATE TABLE tasks(
	id UUID PRIMARY KEY NOT NULL,
	user_id UUID REFERENCES users(id) NOT NULL,
	title VARCHAR(255) NOT NULL,
	description VARCHAR(255) NOT NULL,
	status VARCHAR CHECK (status IN ('PENDING', 'DONE')) DEFAULT 'PENDING' NOT NULL,
	created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
	updated_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL
);

CREATE INDEX idx_tasks_user_id ON tasks(user_id);
